name: Python Test Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MyFramework/requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Pytest
        run: |
          pytest MyFramework/tests --maxfail=1 --disable-warnings -q

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: MyFramework/reports/
